notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a7cbe520877895f3154a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
  email:
    on_success: never
    on_failure: change

script: sh build-package.sh

language: generic

cache:
  timeout: 1000

git:
  depth: 1

os:
  - linux
  - osx
sudo: required

env:
  global:
  matrix:
    - ATOM_SCRIPT_NAME=atom-beta APM_SCRIPT_NAME=apm-beta
    - ATOM_SCRIPT_NAME=atom APM_SCRIPT_NAME=apm

addons:
  apt:
    sources:
    - sourceline: 'deb http://dist.crystal-lang.org/apt crystal main'
    - sourceline: 'deb http://ppa.launchpad.net/avsm/ppa/ubuntu trusty main'
    - sourceline: 'deb http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu trusty main'
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - crystal
    - camlp4
    - aspcud
    - php5-cli
    - golang

cache:
  pip: true
  bundler: true
  directories:
    - vendor/bundle # gems are installed here, https://docs.travis-ci.com/user/languages/ruby/#Dependency-Management
    - node_modules
    - $HOME/.atom
    - $HOME/.opam

before_install:
  # linux: Install Nix, Nix packages, upgrade pip, and install python packages
  # osx: Update Homebrew, remove conflicting cask, brew bundle, symlink elm-format,
  #      upgrade pip, and install python packages
  - echo $TRAVIS_COMMIT_MESSAGE
  - export TRAVIS_COMMIT_MESSAGE=""
  - echo $TRAVIS_COMMIT_MESSAGE
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl https://nixos.org/nix/install | sh &&
      . ~/.nix-profile/etc/profile.d/nix.sh &&
      nix-env -i uncrustify R elm-format terraform atom atom-beta opam &&
      pip install --upgrade pip &&
      pip install --user -r requirements.txt;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update && brew cask zap oclint && brew bundle &&
      ln -s /usr/local/bin/elm-format-0.17 /usr/local/bin/elm-format &&
      pip2 install --upgrade pip &&
      pip2 install -r requirements.txt;
    else
      echo Error:TRAVIS_OS_NAME && exit 1;
    fi
  # Ruby language support
  - bundle install
  # R
  - Rscript --version
  # PHP
  - composer install
  # OCaml
  # - opam init --auto-setup
  # Init environment variables for opam
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  #    eval `opam config env`;
  #  fi
  # - opam install --yes ocp-indent
