language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

before_install:
  - brew update
  - gem install ruby-beautify --verbose
  - brew install python
  - pip install --upgrade autopep8
