language: objective-c

osx_image: xcode7.3

sudo: false

git:
  depth: 10

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a7cbe520877895f3154a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
  email:
    on_success: never
    on_failure: change

script: sh build-package.sh

env:
  global:
    - APM_TEST_PACKAGES="language-marko language-html-swig language-svg language-d mavensmate-atom"
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

cache:
    - pip: true
    - bundler: true
    - directories:
        - vendor/bundle # gems are installed here, https://docs.travis-ci.com/user/languages/ruby/#Dependency-Management
        - node_modules
        - $HOME/.atom
        - $HOME/.stack

before_install:
  # Update Homebrew
  - brew update
  - brew tap homebrew/dupes
  - brew tap homebrew/versions
  # Ruby language support
  # - gem install ruby-beautify --verbose
  - gem install rubocop
  - gem install htmlbeautifier
  - gem install puppet-lint
  # Python language support
  - brew install python
  - pip install --upgrade autopep8
  - pip install --upgrade isort
  # SQL language support
  - pip install --upgrade sqlparse
  # Java, C, C++, C#, Objective-C, D, Pawn, Vala
  - brew install uncrustify
  # PHP
  - brew tap homebrew/homebrew-php
  - brew install php56 || true
  - brew gist-logs php56 || true
  - echo -e "\n[Phar]\nphar.readonly = Off\n" >> /usr/local/etc/php/5.6/php.ini
  - brew install php-cs-fixer || true
  - brew gist-logs php-cs-fixer || true
  # CoffeeScript
  - npm install coffee-formatter
  # Haskell
  # - brew install haskell-stack
  # - stack setup
  # - stack install stylish-haskell
  # Elm
  - curl -L -o /tmp/elm-format.tgz https://github.com/avh4/elm-format/releases/download/0.2.0-alpha/elm-format-0.2.0-alpha-mac-x64.tgz
  - tar xvzf /tmp/elm-format.tgz -C /usr/local/bin
  # OCaml
  - brew install ocaml opam
  - opam init --auto-setup
  - opam install --yes ocp-indent
  # Crystal
  - brew install crystal-lang
