version: "{build}"
os: Windows Server 2012 R2

test: off
deploy: off

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

    # - PYTHON: "C:\\Python27-x64"
    #   PYTHON_VERSION: "2.7.8"
    #   PYTHON_ARCH: "64"
    #
    # - PYTHON: "C:\\Python33"
    #   PYTHON_VERSION: "3.3.5"
    #   PYTHON_ARCH: "32"
    #
    # - PYTHON: "C:\\Python33-x64"
    #   PYTHON_VERSION: "3.3.5"
    #   PYTHON_ARCH: "64"
    #
    # - PYTHON: "C:\\Python34"
    #   PYTHON_VERSION: "3.4.1"
    #   PYTHON_ARCH: "32"
    #
    # - PYTHON: "C:\\Python34-x64"
    #   PYTHON_VERSION: "3.4.1"
    #   PYTHON_ARCH: "64"

init:
  - cmd: rd /s /q %CHOCOLATEYINSTALL%
  - ps: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))

install:

  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  - cinst atom -y
  - cd %APPVEYOR_BUILD_FOLDER%
  # Add Atom's bin (apm, etc) to PATH
  - SET PATH=%LOCALAPPDATA%\atom\bin;%PATH%
  - apm install

  # Install CLI beautifiers

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - "powershell ./appveyor/install.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - "%CMD_IN_ENV% pip install --upgrade autopep8"
  - where autopep8

  # Ruby & Gem
  - cinst ruby -y
  - "SET PATH=C:\\Ruby193\\bin;%PATH%"
  # Rubocop
  - gem install rubocop
  - where rubocop
  # HTMLBeautifier
  - gem install htmlbeautifier
  - where htmlbeautifier
  # Puppet-Lint
  - gem install puppet-lint
  - where puppet-lint

  # emacs
  - cinst emacs -y
  - where emacs

  # PHP
  - cinst php -y
  - ps: "ls \"C:\\tools\\php\""
  - "SET PATH=C:\\tools\\php;%PATH%"
  - where php
  # PHP-CS-Fixer
  - cinst curl -y # Use cURL to download file from URL
  - curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer
  - "SET PATH=%cd%;%PATH%" # Add current working directory to PATH
  - where php-cs-fixer

  # Uncrustify
  - curl -L http://sourceforge.net/projects/uncrustify/files/uncrustify/uncrustify-0.61/uncrustify-0.61.3-gf65394e-win32.zip/download > uncrustify.zip
  - cinst 7zip.commandline -y
  - 7za e uncrustify.zip -ouncrustify
  - "SET PATH=%cd%\\uncrustify;%PATH%"
  - where uncrustify

build_script:

  - cd %APPVEYOR_BUILD_FOLDER%
  # Install languages to Atom
  - apm install language-marko language-html-swig language-svg
  # Show current PATH
  - echo %PATH%
  # Run tests on package
  - apm test --path %LOCALAPPDATA%/atom/bin/atom.cmd
